///////////////////////////////////////////////////////////////////////////////
//
// Dump OscProb PMNS_Maltoni averages (AvgProbLoE, default precision 1e-4,
// Taylor averaging) as a C++ header for tests/test_analytic.cpp:
//
//   dump_maltoni > tests/maltoni_reference.h
//
// Cases: Sterile at dm41 = 1.3 eV^2 (sterile_phases_mix) on 810 km,
// Sterile at dm41 = 0.1 eV^2 (sterile_mix) on 1 km, Fast (NuFIT 5.2 NO)
// on 1300 km; neutrinos and antineutrinos; all channels P[a][b] = P(a -> b).
//
///////////////////////////////////////////////////////////////////////////////

#include <cmath>
#include <cstdio>
#include <vector>

#include "PMNS_Fast.h"
#include "PMNS_Sterile.h"

using namespace OscProb;

static void SetNominalPars(PMNS_Base* p)
{
  p->SetDm(2, 7.41e-5);
  p->SetDm(3, 2.507e-3);
  p->SetAngle(1, 2, asin(sqrt(0.303)));
  p->SetAngle(1, 3, asin(sqrt(0.02225)));
  p->SetAngle(2, 3, asin(sqrt(0.451)));
  p->SetDelta(1, 3, 232 * M_PI / 180);
}

struct Case {
    const char*         name;
    PMNS_Base*          p;
    int                 N;
    double              L, rho, zoa;
    std::vector<double> loe, dloe;
};

int main()
{
  auto s1 = new PMNS_Sterile(4);  // tests/variants.h sterile_phases_mix
  SetNominalPars(s1);
  s1->SetDm(4, 1.3);
  s1->SetAngle(1, 4, 0.15);
  s1->SetAngle(2, 4, 0.2);
  s1->SetAngle(3, 4, 0.3);
  s1->SetDelta(1, 4, 0.9);
  s1->SetDelta(2, 4, -1.7);
  auto s2 = new PMNS_Sterile(4);  // sterile_mix
  SetNominalPars(s2);
  s2->SetDm(4, 0.1);
  s2->SetAngle(1, 4, 0.1);
  s2->SetAngle(2, 4, 0.1);
  s2->SetAngle(3, 4, 0.1);
  auto f = new PMNS_Fast();
  SetNominalPars(f);

  std::vector<Case> cases = {
      {"sterile_fd", s1, 4, 810, 2.84, 0.5, {50, 200, 405, 1000, 3000}, {10, 18, 18, 100, 500}},
      {"sterile_nd", s2, 4, 1, 2.84, 0.5, {0.5, 2, 4}, {0.1, 0.5, 2}},
      {"fast_1300", f, 3, 1300, 2.8, 0.5, {100, 400, 800, 2000}, {20, 40, 80, 400}},
  };

  printf("// Generated by reference/dump_maltoni.cxx from OscProb PMNS_Maltoni.\n");
  printf("#ifndef OPG_TESTS_MALTONI_REFERENCE_H\n#define OPG_TESTS_MALTONI_REFERENCE_H\n\n");
  printf("namespace maltoni_ref {\n\n");
  for (auto& c : cases) {
    c.p->SetUseCache(false);
    c.p->SetPath(NuPath(c.L, c.rho, c.zoa));
    // OscProb returns NaN on the first AvgProbLoE call after SetPath (the
    // K-matrix state is not yet initialised); later calls are fine.
    c.p->AvgProbLoE(0, 0, c.loe[0], c.dloe[0]);
    printf("  // %s: L = %g km, rho = %g, Z/A = %g; [nubar][bin][a][b]\n", c.name, c.L,
           c.rho, c.zoa);
    printf("  constexpr double %s_loe[] = {", c.name);
    for (double v : c.loe) printf("%.17g, ", v);
    printf("};\n  constexpr double %s_dloe[] = {", c.name);
    for (double v : c.dloe) printf("%.17g, ", v);
    printf("};\n  constexpr double %s[] = {\n", c.name);
    for (int nb = 0; nb < 2; nb++) {
      c.p->SetIsNuBar(nb);
      for (size_t i = 0; i < c.loe.size(); i++) {
        printf("     ");
        for (int a = 0; a < c.N; a++)
          for (int b = 0; b < c.N; b++)
            printf(" %.17g,", c.p->AvgProbLoE(a, b, c.loe[i], c.dloe[i]));
        printf("\n");
      }
    }
    printf("  };\n\n");
  }
  printf("} // namespace maltoni_ref\n\n#endif\n");
}
